# Generated by Django 4.0.4 on 2022-11-06 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaomApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='ListApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taom_nomi', models.CharField(max_length=50)),
                ('narx', models.CharField(blank=True, max_length=50, null=True)),
                ('des', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='images/')),
                ('taom_turi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_app.taomapi')),
            ],
        ),
    ]
