# Generated by Django 4.0.4 on 2022-11-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listapi',
            old_name='narx',
            new_name='narx_ar',
        ),
        migrations.RenameField(
            model_name='listapi',
            old_name='taom_nomi',
            new_name='taom_nomi_ar',
        ),
        migrations.RemoveField(
            model_name='listapi',
            name='des',
        ),
        migrations.AddField(
            model_name='listapi',
            name='des_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='des_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='des_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='des_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='narx_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='narx_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='narx_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listapi',
            name='taom_nomi_en',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listapi',
            name='taom_nomi_ru',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listapi',
            name='taom_nomi_uz',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
