# Generated by Django 4.0.4 on 2022-11-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_rename_narx_listapi_narx_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapi',
            name='taom_nomi_ar',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listapi',
            name='taom_nomi_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listapi',
            name='taom_nomi_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listapi',
            name='taom_nomi_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
